### ISSUE TITLE
Config for loop closure in indoor environments

### ISSUE THREAD

**Issue by radparker** [PRBonn/kiss-slam#17]
Hey all, many thanks for your contributions. We've been using KISS-ICP on some indoor datasets and it works pretty well but there are certain areas of the indoor environment where error accumulates and the trajectory drifts. I've been experimenting with KISS-SLAM to see if it can detect and close loops to help correct the drift. Do you have some recommendations on a good config for indoor environments? For example, the splitting_distance likely needs to be lowered from 100 meters. When we do that, and retain the same voxel size, for ex 0.15 m, then we do see loop closures happening but there are many false positives. What other values in the config might you suggest that we adjust if we focus on indoor mapping? Thanks!

**Comment by saurabh1002** [comment]
Hi @radparker, thanks for using our works. We are working on providing an indoor configuration for public use soon. Until then, I would recommend using the following parameters for the KISS odometry and local-mapping within KISS-SLAM to see if it improves your results.

You can save the config below into a `config.yml` file and pass it to the `kiss_slam_pipeline` with a `--config` option.

```yaml
out_dir: slam_output

odometry:
  data:
    deskew: true
    max_range: 50.0
    min_range: 0.0
  mapping:
    max_points_per_voxel: 20
    voxel_size: 0.5

local_mapper:
  voxel_size: 0.5
  splitting_distance: 5.0
```

Additionally, it would be great if you could share the indoor dataset you are using or at least provide more information about it. This would allow us to investigate and improve our pipeline for even better performance.
